name: Validate hello.txt

on:
  pull_request:
    branches:
      - main  # mainブランチへのPRがトリガー

jobs:
  validate-hello-txt:
    runs-on: ubuntu-latest

    steps:
      # コードをリポジトリから取得
      - name: Checkout code
        uses: actions/checkout@v3

      # hello.txt が存在し、1 行目を検証
      - name: Validate first line of hello.txt
        run: |
          if [[ ! -f hello.txt ]]; then
            echo "❌ Error: hello.txt does not exist."
            exit 1
          fi

          first_line=$(head -n 1 hello.txt)

          # 必要な文字列に置き換える例: "Hello GitHub"
          if [[ "$first_line" != "Hello GitHub" ]]; then
            echo "❌ Error: The first line of hello.txt is invalid."
            echo "Found: $first_line"
            exit 1
          fi

          echo "✅ Success: The first line of hello.txt is valid."